# -*- coding: utf-8 -*-
"""Harrypotter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p4ry8OmsM8E3hFTuHOViWrvp4Fwpf3Ip
"""

with open('harry_potter.txt','r') as f:
  hi=f.read()

hi

splitted_data=hi.split('\n')

splitted_data

title=splitted_data[0]
title

author=splitted_data[-1]
author

titleyear=splitted_data[1:-1]
titleyear

D={}
i=0
for i in range(len(titleyear)):
  a=title + ' ' +str(i+1)
  D[a]=None
D

titlelist=[]
yearlist=[]
for i in titleyear:
  title=i.split('(')[0].strip()
  titlelist.append(title)
  years=i.split('(')[1][:-1]
  yearlist.append(years)
print(titlelist)
yearlist

titlelist

yearlist

i=0
for key in D:
  D[key]={"title":titlelist[i],"year":yearlist[i],"author":author}
  i+=1
D

for i in D:
  print(i,D[i])

